export interface Artwork{
  id: number,
  "title": string,
  "description": string,
  "author": string,
  "creationDate": string,
  "incorporatedDate": string,
  "period": string,
  "assessment": number,
  "image": string,
  "type": number,
  "style": string,
  "media": string,
  "material": string,
  "status": number,
  "room": string,
}