// <auto-generated />
using System;
using IMuseum.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMuseum.Persistence.Migrations
{
    [DbContext(typeof(IMuseumContext))]
    [Migration("20220627202329_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("IMuseum.Persistence.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Assessment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentSatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IncorporatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MuseumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.HasIndex("RoomId");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7944),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            Images = "",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 2,
                            Title = "The tapice 1"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7973),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            Images = "",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 3,
                            Title = "The tapice 2"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7986),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            Images = "",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 1,
                            Title = "The tapice 3"
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7999),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            Images = "",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 2,
                            Title = "The tapice 4"
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8011),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            Images = "",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 3,
                            Title = "The tapice 5"
                        },
                        new
                        {
                            Id = 6,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8024),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            Images = "",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 1,
                            Title = "The tapice 6"
                        },
                        new
                        {
                            Id = 7,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8035),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            Images = "",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 2,
                            Title = "The tapice 7"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoanApplicationId")
                        .IsUnique();

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7685),
                            Deleted = false,
                            LoanApplicationId = 1,
                            PaymentAmount = 10m,
                            StartDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7691),
                            Deleted = false,
                            LoanApplicationId = 2,
                            PaymentAmount = 20m,
                            StartDate = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MuseumId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("MuseumId");

                    b.ToTable("LoanApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7708),
                            ApplicationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ArtworkId = 1,
                            CurrentStatus = 0,
                            Deleted = false,
                            Duration = 10,
                            MuseumId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7712),
                            ApplicationDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ArtworkId = 1,
                            CurrentStatus = 0,
                            Deleted = false,
                            Duration = 10,
                            MuseumId = 1
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Museum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Museums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7473),
                            Deleted = false,
                            Name = "Louvre Museum"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7518),
                            Deleted = false,
                            Name = "British Museum"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7521),
                            Deleted = false,
                            Name = "London Arqueology Museum"
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7522),
                            Deleted = false,
                            Name = "New York Museum"
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7524),
                            Deleted = false,
                            Name = "Vatican City Museum"
                        },
                        new
                        {
                            Id = 6,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7526),
                            Deleted = false,
                            Name = "Kiko's Gallery"
                        },
                        new
                        {
                            Id = 7,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7528),
                            Deleted = false,
                            Name = "LeTize Museum"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Restoration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.ToTable("Restorations");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7658),
                            Deleted = false,
                            Name = "Director"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7662),
                            Deleted = false,
                            Name = "Restaurator Sheef"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7664),
                            Deleted = false,
                            Name = "Catalog Manager"
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7666),
                            Deleted = false,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7668),
                            Deleted = false,
                            Name = "Visiter"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8211),
                            Deleted = false,
                            Name = "Davinci"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8213),
                            Deleted = false,
                            Name = "Gallery"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8215),
                            Deleted = false,
                            Name = "Galileo"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8227),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "admin.psw123//",
                            RoleId = 4,
                            Username = "Foreman Administrator"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8230),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "manager.psw123//",
                            RoleId = 3,
                            Username = "Lorena Manager"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8233),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "restaurator.psw123//",
                            RoleId = 2,
                            Username = "Juan Restaurator"
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8235),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "director.psw123//",
                            RoleId = 1,
                            Username = "Harvey Director"
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8237),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "restaurator.psw123//",
                            RoleId = 2,
                            Username = "Pablo Restaurator"
                        },
                        new
                        {
                            Id = 6,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8239),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "manager.psw123//",
                            RoleId = 3,
                            Username = "Dorian Manager"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Painting", b =>
                {
                    b.HasBaseType("IMuseum.Persistence.Models.Artwork");

                    b.Property<string>("Media")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Paintings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 19,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7745),
                            Assessment = 10m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:265/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/Leonardo-Da-Vinci-Mona-Lisa.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 6,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Mona Lisa (La Gioconda)",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 18,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7764),
                            Assessment = 9m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:500/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/Vincent-Van-Gogh-Starry-Night.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 5,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Starry-Night",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 17,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7776),
                            Assessment = 8m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:316/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/Edvard-Munch-The-Scream.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 4,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "The Scream",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 16,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7787),
                            Assessment = 7m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:443/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/PabloPicasso-ThreeMusicians.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 3,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Three Musicians",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 15,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7799),
                            Assessment = 6m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:347/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/Jan-Vermeer-The-Girl-with-a-Pearl-Earring.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 2,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "The Girl with a Pearl Earring",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 14,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7811),
                            Assessment = 5m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:492/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/Rembrandt_Van_Rijn-Night_Watch_.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Night Watch",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 13,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7822),
                            Assessment = 4m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:398/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/Gustav-Klimt-The-Kiss-Bacio-.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 7,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "The Kiss (Bacio)",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 12,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7833),
                            Assessment = 3m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:413/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/Claude-Monet-Water-Lilies.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 6,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Water Lilies",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 11,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7914),
                            Assessment = 2m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:592/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/Georges-Seurat-A-Sunday-Afternoon-on-the-Island-of-La-Grande-Jatte.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 5,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "A Sunday Afternoon on the Island of La Grande Jatte",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 10,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(7929),
                            Assessment = 1m,
                            Author = "Author",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "https://mljecheddetu.i.optimole.com/r7ifq_I.35uE~1b08/w:331/h:400/q:mauto/https://www.justincanvas.com/wp-content/uploads/2020/03/Grant-Wood-American-Gothic.jpg",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 4,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "American Gothic",
                            Media = "address",
                            Style = "Renacence"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Sculpture", b =>
                {
                    b.HasBaseType("IMuseum.Persistence.Models.Artwork");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Sculptures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 20,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8051),
                            Assessment = 1m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa20",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 21,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8067),
                            Assessment = 2m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Monalisa21",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 22,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8079),
                            Assessment = 3m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa22",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 23,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8091),
                            Assessment = 4m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa23",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 24,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8102),
                            Assessment = 5m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Monalisa24",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 25,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8115),
                            Assessment = 6m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa25",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 26,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8126),
                            Assessment = 7m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa26",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 27,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8173),
                            Assessment = 8m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Monalisa27",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 28,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8186),
                            Assessment = 9m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa28",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 29,
                            AddTime = new DateTime(2022, 6, 27, 16, 23, 28, 614, DateTimeKind.Local).AddTicks(8199),
                            Assessment = 10m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            Images = "",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa29",
                            Material = "Gold",
                            Style = "Style"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Artwork", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Museum", "Museum")
                        .WithMany("Artworks")
                        .HasForeignKey("MuseumId");

                    b.HasOne("IMuseum.Persistence.Models.Room", "Room")
                        .WithMany("Artworks")
                        .HasForeignKey("RoomId");

                    b.Navigation("Museum");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Loan", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.LoanApplication", "Application")
                        .WithOne("LoanRelated")
                        .HasForeignKey("IMuseum.Persistence.Models.Loan", "LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.LoanApplication", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Artwork", "Artwork")
                        .WithMany("LoanApplications")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMuseum.Persistence.Models.Museum", "RelatedMuseum")
                        .WithMany("LoanApplications")
                        .HasForeignKey("MuseumId");

                    b.Navigation("Artwork");

                    b.Navigation("RelatedMuseum");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Restoration", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Artwork", "Artwork")
                        .WithMany("Restorations")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.User", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Role", "Role")
                        .WithMany("RelatedUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Painting", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Artwork", null)
                        .WithOne()
                        .HasForeignKey("IMuseum.Persistence.Models.Painting", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Sculpture", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Artwork", null)
                        .WithOne()
                        .HasForeignKey("IMuseum.Persistence.Models.Sculpture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Artwork", b =>
                {
                    b.Navigation("LoanApplications");

                    b.Navigation("Restorations");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.LoanApplication", b =>
                {
                    b.Navigation("LoanRelated");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Museum", b =>
                {
                    b.Navigation("Artworks");

                    b.Navigation("LoanApplications");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Role", b =>
                {
                    b.Navigation("RelatedUsers");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Room", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
