// <auto-generated />
using System;
using IMuseum.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMuseum.Persistence.Migrations
{
    [DbContext(typeof(IMuseumContext))]
    [Migration("20220627035917_SecondSeedingMigration")]
    partial class SecondSeedingMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("IMuseum.Persistence.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Assessment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentSatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IncorporatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MuseumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.HasIndex("RoomId");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2704),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 2,
                            Title = "The tapice 1"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2742),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 3,
                            Title = "The tapice 2"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2770),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 1,
                            Title = "The tapice 3"
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2796),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 2,
                            Title = "The tapice 4"
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2821),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 3,
                            Title = "The tapice 5"
                        },
                        new
                        {
                            Id = 6,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2850),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 1,
                            Title = "The tapice 6"
                        },
                        new
                        {
                            Id = 7,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2878),
                            Assessment = 10m,
                            Author = "Unknown",
                            CreationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 1,
                            Deleted = false,
                            Description = "It is just biuriful.",
                            IncorporatedDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "ooold",
                            RoomId = 2,
                            Title = "The tapice 7"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2468),
                            ArtworkId = 3,
                            Bytes = new byte[] { 0 },
                            Deleted = false,
                            FileExtension = "",
                            Size = 3L,
                            Title = "Title"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2475),
                            ArtworkId = 3,
                            Bytes = new byte[] { 0 },
                            Deleted = false,
                            FileExtension = "",
                            Size = 3L,
                            Title = "Title"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2480),
                            ArtworkId = 3,
                            Bytes = new byte[] { 0 },
                            Deleted = false,
                            FileExtension = "",
                            Size = 3L,
                            Title = "Title"
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2484),
                            ArtworkId = 3,
                            Bytes = new byte[] { 0 },
                            Deleted = false,
                            FileExtension = "",
                            Size = 3L,
                            Title = "Title"
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2489),
                            ArtworkId = 3,
                            Bytes = new byte[] { 0 },
                            Deleted = false,
                            FileExtension = "",
                            Size = 3L,
                            Title = "Title"
                        },
                        new
                        {
                            Id = 6,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2494),
                            ArtworkId = 3,
                            Bytes = new byte[] { 0 },
                            Deleted = false,
                            FileExtension = "",
                            Size = 3L,
                            Title = "Title"
                        },
                        new
                        {
                            Id = 7,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2498),
                            ArtworkId = 3,
                            Bytes = new byte[] { 0 },
                            Deleted = false,
                            FileExtension = "",
                            Size = 3L,
                            Title = "Title"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanAplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8758),
                            Deleted = false,
                            LoanAplicationId = 1,
                            PaymentAmount = 10m,
                            StartDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8766),
                            Deleted = false,
                            LoanAplicationId = 2,
                            PaymentAmount = 20m,
                            StartDate = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuseumId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("LoanId")
                        .IsUnique();

                    b.HasIndex("MuseumId");

                    b.ToTable("LoanApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8786),
                            ApplicationDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ArtworkId = 1,
                            CurrentStatus = 0,
                            Deleted = false,
                            Duration = 10,
                            LoanId = 1,
                            MuseumId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8792),
                            ApplicationDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ArtworkId = 1,
                            CurrentStatus = 0,
                            Deleted = false,
                            Duration = 10,
                            LoanId = 2,
                            MuseumId = 1
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Museum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Museums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8474),
                            Deleted = false,
                            Name = "Louvre Museum"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8508),
                            Deleted = false,
                            Name = "British Museum"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8511),
                            Deleted = false,
                            Name = "London Arqueology Museum"
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8513),
                            Deleted = false,
                            Name = "New York Museum"
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8515),
                            Deleted = false,
                            Name = "Vatican City Museum"
                        },
                        new
                        {
                            Id = 6,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8518),
                            Deleted = false,
                            Name = "Kiko's Gallery"
                        },
                        new
                        {
                            Id = 7,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8520),
                            Deleted = false,
                            Name = "LeTize Museum"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Restoration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.ToTable("Restorations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2421),
                            ArtworkId = 3,
                            Deleted = false,
                            EndDate = new DateTime(2012, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2012, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2429),
                            ArtworkId = 4,
                            Deleted = false,
                            EndDate = new DateTime(2015, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2014, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2435),
                            ArtworkId = 5,
                            Deleted = false,
                            EndDate = new DateTime(2011, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2011, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8657),
                            Deleted = false,
                            Name = "Director"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8666),
                            Deleted = false,
                            Name = "Restaurator Sheef"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8669),
                            Deleted = false,
                            Name = "Catalog Manager"
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8671),
                            Deleted = false,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 395, DateTimeKind.Local).AddTicks(8673),
                            Deleted = false,
                            Name = "Visiter"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2376),
                            Deleted = false,
                            Name = "Davinci"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2383),
                            Deleted = false,
                            Name = "Gallery"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2387),
                            Deleted = false,
                            Name = "Galileo"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2544),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "admin.psw123//",
                            Username = "Foreman Administrator"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2551),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "manager.psw123//",
                            Username = "Lorena Manager"
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2555),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "restaurator.psw123//",
                            Username = "Juan Restaurator"
                        },
                        new
                        {
                            Id = 4,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2560),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "director.psw123//",
                            Username = "Harvey Director"
                        },
                        new
                        {
                            Id = 5,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2565),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "restaurator.psw123//",
                            Username = "Pablo Restaurator"
                        },
                        new
                        {
                            Id = 6,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2570),
                            Deleted = false,
                            Email = "example@gmail.com",
                            Password = "manager.psw123//",
                            Username = "Dorian Manager"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RelatedUsersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelatedUsersId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Painting", b =>
                {
                    b.HasBaseType("IMuseum.Persistence.Models.Artwork");

                    b.Property<string>("Media")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2233),
                            Assessment = 1m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 4,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa10",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 11,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2426),
                            Assessment = 2m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 5,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa11",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 12,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2468),
                            Assessment = 3m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 6,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Monalisa12",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 13,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2497),
                            Assessment = 4m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 7,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa13",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 14,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2524),
                            Assessment = 5m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa14",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 15,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2558),
                            Assessment = 6m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 2,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Monalisa15",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 16,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2587),
                            Assessment = 7m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 3,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa16",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 17,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2614),
                            Assessment = 8m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 4,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa17",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 18,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2640),
                            Assessment = 9m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 5,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Monalisa18",
                            Media = "address",
                            Style = "Renacence"
                        },
                        new
                        {
                            Id = 19,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 399, DateTimeKind.Local).AddTicks(2671),
                            Assessment = 10m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 6,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa19",
                            Media = "address",
                            Style = "Renacence"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Sculpture", b =>
                {
                    b.HasBaseType("IMuseum.Persistence.Models.Artwork");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Sculpture");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(1916),
                            Assessment = 1m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa20",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 21,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2012),
                            Assessment = 2m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Monalisa21",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 22,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2046),
                            Assessment = 3m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa22",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 23,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2072),
                            Assessment = 4m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa23",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 24,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2098),
                            Assessment = 5m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Monalisa24",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 25,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2130),
                            Assessment = 6m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa25",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 26,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2158),
                            Assessment = 7m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa26",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 27,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2187),
                            Assessment = 8m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 1,
                            Title = "Monalisa27",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 28,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2299),
                            Assessment = 9m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 2,
                            Title = "Monalisa28",
                            Material = "Gold",
                            Style = "Style"
                        },
                        new
                        {
                            Id = 29,
                            AddTime = new DateTime(2022, 6, 26, 23, 59, 16, 402, DateTimeKind.Local).AddTicks(2345),
                            Assessment = 10m,
                            Author = "Leonardo da Vinci",
                            CreationDate = new DateTime(1503, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentSatus = 3,
                            Deleted = false,
                            Description = "Estalin Disima",
                            IncorporatedDate = new DateTime(2002, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MuseumId = 1,
                            Period = "Renacence",
                            RoomId = 3,
                            Title = "Monalisa29",
                            Material = "Gold",
                            Style = "Style"
                        });
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Artwork", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Museum", "Museum")
                        .WithMany("Artworks")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMuseum.Persistence.Models.Room", "Room")
                        .WithMany("Artworks")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Image", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Artwork", "Artwork")
                        .WithMany("Images")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.LoanApplication", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Artwork", "Artwork")
                        .WithMany("LoanApplications")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMuseum.Persistence.Models.Loan", "LoanRelated")
                        .WithOne("Application")
                        .HasForeignKey("IMuseum.Persistence.Models.LoanApplication", "LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMuseum.Persistence.Models.Museum", "RelatedMuseum")
                        .WithMany("LoanApplications")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("LoanRelated");

                    b.Navigation("RelatedMuseum");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Restoration", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Artwork", "Artwork")
                        .WithMany("Restorations")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RelatedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMuseum.Persistence.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Painting", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Artwork", null)
                        .WithOne()
                        .HasForeignKey("IMuseum.Persistence.Models.Painting", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Sculpture", b =>
                {
                    b.HasOne("IMuseum.Persistence.Models.Artwork", null)
                        .WithOne()
                        .HasForeignKey("IMuseum.Persistence.Models.Sculpture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Artwork", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LoanApplications");

                    b.Navigation("Restorations");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Loan", b =>
                {
                    b.Navigation("Application")
                        .IsRequired();
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Museum", b =>
                {
                    b.Navigation("Artworks");

                    b.Navigation("LoanApplications");
                });

            modelBuilder.Entity("IMuseum.Persistence.Models.Room", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
